// export const restaurantList = [
//   {
//     type: "restaurant",
//     data: {
//       type: "F",
//       id: "580637",
//       name: "Good Flippin' Burgers",
//       uuid: "d2a8ac8e-edd7-466a-b88d-9246bf8b8e08",
//       city: "5",
//       area: "Vashi",
//       totalRatingsString: "100+ ratings",
//       cloudinaryImageId: "qit5j48tjgoquzaau9j6",
//       cuisines: ["Burgers", "American", "Fast Food", "Beverages"],
//       tags: [],
//       costForTwo: 60000,
//       costForTwoString: "₹600 FOR TWO",
//       deliveryTime: 30,
//       minDeliveryTime: 30,
//       maxDeliveryTime: 30,
//       slaString: "30 MINS",
//       lastMileTravel: 4.5,
//       slugs: {
//         restaurant: "good-flippin’-burgers-vashi-vashi",
//         city: "mumbai",
//       },
//       cityState: "5",
//       address:
//         "Shop No 38 & 41, Shiv CenterPremises, Plot No. 72, Sector 17, Vashi, Navi Mumbai",
//       locality: "Vashi",
//       parentId: 11748,
//       unserviceable: false,
//       veg: false,
//       select: false,
//       favorite: false,
//       tradeCampaignHeaders: [],
//       aggregatedDiscountInfo: {
//         header: "50% off",
//         shortDescriptionList: [
//           {
//             meta: "50% off | Use WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "50% off up to ₹100 | Use code WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       aggregatedDiscountInfoV2: {
//         header: "50% OFF",
//         shortDescriptionList: [
//           {
//             meta: "Use WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "50% off up to ₹100 | Use code WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       ribbon: [
//         {
//           type: "PROMOTED",
//         },
//       ],
//       chain: [],
//       feeDetails: {
//         fees: [],
//         totalFees: 0,
//         message: "",
//         title: "",
//         amount: "",
//         icon: "",
//       },
//       availability: {
//         opened: true,
//         nextOpenMessage: "",
//         nextCloseMessage: "",
//       },
//       longDistanceEnabled: 0,
//       rainMode: "NONE",
//       thirdPartyAddress: false,
//       thirdPartyVendor: "",
//       adTrackingID: "cid=5682697~p=1~eid=00000185-8b34-0265-0ed7-a87e00b80158",
//       badges: {
//         imageBased: [],
//         textBased: [],
//         textExtendedBadges: [],
//       },
//       lastMileTravelString: "4.5 kms",
//       hasSurge: false,
//       sla: {
//         restaurantId: "580637",
//         deliveryTime: 30,
//         minDeliveryTime: 30,
//         maxDeliveryTime: 30,
//         lastMileTravel: 4.5,
//         lastMileDistance: 0,
//         serviceability: "SERVICEABLE",
//         rainMode: "NONE",
//         longDistance: "NOT_LONG_DISTANCE",
//         preferentialService: false,
//         iconType: "EMPTY",
//       },
//       promoted: true,
//       avgRating: "4.5",
//       totalRatings: 100,
//       new: false,
//     },
//     subtype: "basic",
//   },
//   {
//     type: "restaurant",
//     data: {
//       type: "F",
//       id: "30240",
//       name: "McDonald's",
//       uuid: "4aea1eeb-78cf-40af-88d0-ed5db49ee162",
//       city: "5",
//       area: "Kopar Khairane",
//       totalRatingsString: "1000+ ratings",
//       cloudinaryImageId: "7bb739d7f6ae8b4ce8ed590765dffd2f",
//       cuisines: ["Burgers", "Beverages", "Cafe", "Desserts"],
//       tags: [],
//       costForTwo: 40000,
//       costForTwoString: "₹400 FOR TWO",
//       deliveryTime: 16,
//       minDeliveryTime: 16,
//       maxDeliveryTime: 16,
//       slaString: "16 MINS",
//       lastMileTravel: 1.399999976158142,
//       slugs: {
//         restaurant: "mcdonalds-koparkhairane-vashi",
//         city: "mumbai",
//       },
//       cityState: "5",
//       address:
//         "Balaji Multiplex, Plot #90, Sector #8, Kopar Khairane, Navi Mumbai- 400709",
//       locality: "Koparkhairane",
//       parentId: 630,
//       unserviceable: false,
//       veg: false,
//       select: false,
//       favorite: false,
//       tradeCampaignHeaders: [],
//       aggregatedDiscountInfo: {
//         header: "50% off",
//         shortDescriptionList: [
//           {
//             meta: "50% off | Use WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "50% off up to ₹100 | Use code WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       aggregatedDiscountInfoV2: {
//         header: "50% OFF",
//         shortDescriptionList: [
//           {
//             meta: "Use WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "50% off up to ₹100 | Use code WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       chain: [],
//       feeDetails: {
//         fees: [],
//         totalFees: 0,
//         message: "",
//         title: "",
//         amount: "",
//         icon: "",
//       },
//       availability: {
//         opened: true,
//         nextOpenMessage: "",
//         nextCloseMessage: "",
//       },
//       longDistanceEnabled: 0,
//       rainMode: "NONE",
//       thirdPartyAddress: false,
//       thirdPartyVendor: "",
//       adTrackingID: "",
//       badges: {
//         imageBased: [],
//         textBased: [],
//         textExtendedBadges: [],
//       },
//       lastMileTravelString: "1.3 kms",
//       hasSurge: false,
//       sla: {
//         restaurantId: "30240",
//         deliveryTime: 16,
//         minDeliveryTime: 16,
//         maxDeliveryTime: 16,
//         lastMileTravel: 1.399999976158142,
//         lastMileDistance: 0,
//         serviceability: "SERVICEABLE",
//         rainMode: "NONE",
//         longDistance: "NOT_LONG_DISTANCE",
//         preferentialService: false,
//         iconType: "EMPTY",
//       },
//       promoted: false,
//       avgRating: "4.4",
//       totalRatings: 1000,
//       new: false,
//     },
//     subtype: "basic",
//   },
//   {
//     type: "restaurant",
//     data: {
//       type: "F",
//       id: "73404",
//       name: "Bismillah Catering",
//       uuid: "0b995a4b-1c4c-4c01-974d-932062c952cb",
//       city: "5",
//       area: "Ghansoli",
//       totalRatingsString: "500+ ratings",
//       cloudinaryImageId: "g3og70yawe2wxxgqzxtr",
//       cuisines: ["Biryani", "Indian"],
//       tags: [],
//       costForTwo: 55000,
//       costForTwoString: "₹550 FOR TWO",
//       deliveryTime: 18,
//       minDeliveryTime: 18,
//       maxDeliveryTime: 18,
//       slaString: "18 MINS",
//       lastMileTravel: 2.299999952316284,
//       slugs: {
//         restaurant: "bismillah-catering-ghansoli-vashi",
//         city: "mumbai",
//       },
//       cityState: "5",
//       address:
//         "Bismillah Catering, Shop 14,Near Dargah, Sector 1, Ghansoli, Navi Mumbai",
//       locality: "Sector 1",
//       parentId: 6200,
//       unserviceable: false,
//       veg: false,
//       select: false,
//       favorite: false,
//       tradeCampaignHeaders: [],
//       aggregatedDiscountInfo: {
//         header: "50% off",
//         shortDescriptionList: [
//           {
//             meta: "50% off | Use WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "50% off up to ₹100 | Use code WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       aggregatedDiscountInfoV2: {
//         header: "50% OFF",
//         shortDescriptionList: [
//           {
//             meta: "Use WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "50% off up to ₹100 | Use code WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       chain: [],
//       feeDetails: {
//         fees: [],
//         totalFees: 0,
//         message: "",
//         title: "",
//         amount: "",
//         icon: "",
//       },
//       availability: {
//         opened: true,
//         nextOpenMessage: "",
//         nextCloseMessage: "",
//       },
//       longDistanceEnabled: 0,
//       rainMode: "NONE",
//       thirdPartyAddress: false,
//       thirdPartyVendor: "",
//       adTrackingID: "",
//       badges: {
//         imageBased: [],
//         textBased: [],
//         textExtendedBadges: [],
//       },
//       lastMileTravelString: "2.2 kms",
//       hasSurge: false,
//       sla: {
//         restaurantId: "73404",
//         deliveryTime: 18,
//         minDeliveryTime: 18,
//         maxDeliveryTime: 18,
//         lastMileTravel: 2.299999952316284,
//         lastMileDistance: 0,
//         serviceability: "SERVICEABLE",
//         rainMode: "NONE",
//         longDistance: "NOT_LONG_DISTANCE",
//         preferentialService: false,
//         iconType: "EMPTY",
//       },
//       promoted: false,
//       avgRating: "4.0",
//       totalRatings: 500,
//       new: false,
//     },
//     subtype: "basic",
//   },
//   {
//     type: "restaurant",
//     data: {
//       type: "F",
//       id: "608655",
//       name: "Goila Butter Chicken",
//       uuid: "07d0d4ab-5933-4b90-b29b-41540d2cb0ad",
//       city: "5",
//       area: "Vashi",
//       totalRatingsString: "100+ ratings",
//       cloudinaryImageId: "8047952208912b376eb800db0f9a45d0",
//       cuisines: ["North Indian", "Mughlai", "Biryani", "Indian"],
//       tags: [],
//       costForTwo: 60000,
//       costForTwoString: "₹600 FOR TWO",
//       deliveryTime: 38,
//       minDeliveryTime: 38,
//       maxDeliveryTime: 38,
//       slaString: "38 MINS",
//       lastMileTravel: 3,
//       slugs: {
//         restaurant: "goila-butter-chicken-vashi-vashi",
//         city: "mumbai",
//       },
//       cityState: "5",
//       address:
//         "UNIT NO - 174, SATRA PLAZA, PLOT NO - 19/20, SECTOR - 19 D, VASHI, NAVI MUMBAI, Vashi Zone Mumbai Municipal Corporation (Thane Zone-3), Maharashtra-400705",
//       locality: "Vashi",
//       parentId: 322587,
//       unserviceable: false,
//       veg: false,
//       select: false,
//       favorite: false,
//       tradeCampaignHeaders: [],
//       aggregatedDiscountInfo: {
//         header: "50% off",
//         shortDescriptionList: [
//           {
//             meta: "50% off | Use WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "50% off up to ₹100 | Use code WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       aggregatedDiscountInfoV2: {
//         header: "50% OFF",
//         shortDescriptionList: [
//           {
//             meta: "Use WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "50% off up to ₹100 | Use code WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       ribbon: [
//         {
//           type: "PROMOTED",
//         },
//       ],
//       chain: [],
//       feeDetails: {
//         fees: [],
//         totalFees: 0,
//         message: "",
//         title: "",
//         amount: "",
//         icon: "",
//       },
//       availability: {
//         opened: true,
//         nextOpenMessage: "",
//         nextCloseMessage: "",
//       },
//       longDistanceEnabled: 0,
//       rainMode: "NONE",
//       thirdPartyAddress: false,
//       thirdPartyVendor: "",
//       adTrackingID: "cid=5610861~p=4~eid=00000185-8b34-0265-0ed7-a87f00b8040e",
//       badges: {
//         imageBased: [],
//         textBased: [],
//         textExtendedBadges: [],
//       },
//       lastMileTravelString: "3 kms",
//       hasSurge: false,
//       sla: {
//         restaurantId: "608655",
//         deliveryTime: 38,
//         minDeliveryTime: 38,
//         maxDeliveryTime: 38,
//         lastMileTravel: 3,
//         lastMileDistance: 0,
//         serviceability: "SERVICEABLE",
//         rainMode: "NONE",
//         longDistance: "NOT_LONG_DISTANCE",
//         preferentialService: false,
//         iconType: "EMPTY",
//       },
//       promoted: true,
//       avgRating: "4.2",
//       totalRatings: 100,
//       new: false,
//     },
//     subtype: "basic",
//   },
//   {
//     type: "restaurant",
//     data: {
//       type: "F",
//       id: "43742",
//       name: "Laxmi Pure Veg",
//       uuid: "2d40e900-4625-4c7a-9fea-acc825edfe95",
//       city: "5",
//       area: "Kopar Khairane",
//       totalRatingsString: "500+ ratings",
//       cloudinaryImageId: "mjgbfvgvmfgg07xodzd9",
//       cuisines: ["South Indian", "Indian", "Chinese", "Punjabi", "Snacks"],
//       tags: [],
//       costForTwo: 45000,
//       costForTwoString: "₹450 FOR TWO",
//       deliveryTime: 19,
//       minDeliveryTime: 19,
//       maxDeliveryTime: 19,
//       slaString: "19 MINS",
//       lastMileTravel: 0.699999988079071,
//       slugs: {
//         restaurant: "laxmi-pure-veg-kopar-khairane-vashi",
//         city: "mumbai",
//       },
//       cityState: "5",
//       address:
//         "6, Sector 7, Amar Co Operative Housing Society, Kopar Khairane, Navi Mumbai",
//       locality: "Vashi",
//       parentId: 123987,
//       unserviceable: false,
//       veg: true,
//       select: false,
//       favorite: false,
//       tradeCampaignHeaders: [],
//       aggregatedDiscountInfo: {
//         header: "50% off",
//         shortDescriptionList: [
//           {
//             meta: "50% off | Use WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "50% off up to ₹100 | Use code WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       aggregatedDiscountInfoV2: {
//         header: "50% OFF",
//         shortDescriptionList: [
//           {
//             meta: "Use WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "50% off up to ₹100 | Use code WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       chain: [],
//       feeDetails: {
//         fees: [],
//         totalFees: 0,
//         message: "",
//         title: "",
//         amount: "",
//         icon: "",
//       },
//       availability: {
//         opened: true,
//         nextOpenMessage: "",
//         nextCloseMessage: "",
//       },
//       longDistanceEnabled: 0,
//       rainMode: "NONE",
//       thirdPartyAddress: false,
//       thirdPartyVendor: "",
//       adTrackingID: "",
//       badges: {
//         imageBased: [],
//         textBased: [],
//         textExtendedBadges: [],
//       },
//       lastMileTravelString: "0.6 kms",
//       hasSurge: false,
//       sla: {
//         restaurantId: "43742",
//         deliveryTime: 19,
//         minDeliveryTime: 19,
//         maxDeliveryTime: 19,
//         lastMileTravel: 0.699999988079071,
//         lastMileDistance: 0,
//         serviceability: "SERVICEABLE",
//         rainMode: "NONE",
//         longDistance: "NOT_LONG_DISTANCE",
//         preferentialService: false,
//         iconType: "EMPTY",
//       },
//       promoted: false,
//       avgRating: "4.1",
//       totalRatings: 500,
//       new: false,
//     },
//     subtype: "basic",
//   },
//   {
//     type: "restaurant",
//     data: {
//       type: "F",
//       id: "300013",
//       name: "Shree Chaines And Desi",
//       uuid: "7447d4ac-25e0-4a6f-8951-805d5e6ad973",
//       city: "5",
//       area: "Kopar Khairane",
//       totalRatingsString: "20+ ratings",
//       cloudinaryImageId: "ehtcp2suxzu8228rtqwb",
//       cuisines: ["Chinese", "Indian"],
//       tags: [],
//       costForTwo: 15000,
//       costForTwoString: "₹150 FOR TWO",
//       deliveryTime: 25,
//       minDeliveryTime: 25,
//       maxDeliveryTime: 25,
//       slaString: "25 MINS",
//       lastMileTravel: 0.5,
//       slugs: {
//         restaurant: "shree-chaines-and-desi-vashi-vashi",
//         city: "mumbai",
//       },
//       cityState: "5",
//       address:
//         "DVS College of Commerce, Gyan Vikas Road, Sector 17, Kopar Khairane, Navi Mumbai, Maharashtra, India",
//       locality: "Vashi",
//       parentId: 184370,
//       unserviceable: false,
//       veg: false,
//       select: false,
//       favorite: false,
//       tradeCampaignHeaders: [],
//       aggregatedDiscountInfo: {
//         header: "50% off",
//         shortDescriptionList: [
//           {
//             meta: "50% off | Use WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "50% off up to ₹100 | Use code WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       aggregatedDiscountInfoV2: {
//         header: "50% OFF",
//         shortDescriptionList: [
//           {
//             meta: "Use WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "50% off up to ₹100 | Use code WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       chain: [],
//       feeDetails: {
//         fees: [],
//         totalFees: 0,
//         message: "",
//         title: "",
//         amount: "",
//         icon: "",
//       },
//       availability: {
//         opened: true,
//         nextOpenMessage: "",
//         nextCloseMessage: "",
//       },
//       longDistanceEnabled: 0,
//       rainMode: "NONE",
//       thirdPartyAddress: false,
//       thirdPartyVendor: "",
//       adTrackingID: "",
//       badges: {
//         imageBased: [],
//         textBased: [],
//         textExtendedBadges: [],
//       },
//       lastMileTravelString: "0.5 kms",
//       hasSurge: false,
//       sla: {
//         restaurantId: "300013",
//         deliveryTime: 25,
//         minDeliveryTime: 25,
//         maxDeliveryTime: 25,
//         lastMileTravel: 0.5,
//         lastMileDistance: 0,
//         serviceability: "SERVICEABLE",
//         rainMode: "NONE",
//         longDistance: "NOT_LONG_DISTANCE",
//         preferentialService: false,
//         iconType: "EMPTY",
//       },
//       promoted: false,
//       avgRating: "3.5",
//       totalRatings: 20,
//       new: false,
//     },
//     subtype: "basic",
//   },
//   {
//     type: "restaurant",
//     data: {
//       type: "F",
//       id: "52670",
//       name: "Shalin",
//       uuid: "7284d532-8ae3-4868-9ba5-95ba683be738",
//       city: "5",
//       area: "Vashi",
//       totalRatingsString: "100+ ratings",
//       cloudinaryImageId: "ytxn4tnmutzumo1gws9x",
//       cuisines: ["Tandoor", "Biryani", "Indian", "Chinese"],
//       tags: [],
//       costForTwo: 50000,
//       costForTwoString: "₹500 FOR TWO",
//       deliveryTime: 28,
//       minDeliveryTime: 28,
//       maxDeliveryTime: 28,
//       slaString: "28 MINS",
//       lastMileTravel: 4.400000095367432,
//       slugs: {
//         restaurant: "shalin-vashi-vashi",
//         city: "mumbai",
//       },
//       cityState: "5",
//       address:
//         "15/16, Laxman Commercial Complex, MAFCO Market, Sector 18, Vashi, Navi Mumbai",
//       locality: "Mafco Market",
//       parentId: 181395,
//       unserviceable: false,
//       veg: false,
//       select: false,
//       favorite: false,
//       tradeCampaignHeaders: [],
//       aggregatedDiscountInfo: {
//         header: "50% off",
//         shortDescriptionList: [
//           {
//             meta: "50% off | Use WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "50% off up to ₹100 | Use code WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       aggregatedDiscountInfoV2: {
//         header: "50% OFF",
//         shortDescriptionList: [
//           {
//             meta: "Use WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "50% off up to ₹100 | Use code WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       ribbon: [
//         {
//           type: "PROMOTED",
//         },
//       ],
//       chain: [],
//       feeDetails: {
//         fees: [],
//         totalFees: 0,
//         message: "",
//         title: "",
//         amount: "",
//         icon: "",
//       },
//       availability: {
//         opened: true,
//         nextOpenMessage: "",
//         nextCloseMessage: "",
//       },
//       longDistanceEnabled: 0,
//       rainMode: "NONE",
//       thirdPartyAddress: false,
//       thirdPartyVendor: "",
//       adTrackingID: "cid=5687066~p=7~eid=00000185-8b34-0265-0ed7-a88000b8070f",
//       badges: {
//         imageBased: [],
//         textBased: [],
//         textExtendedBadges: [],
//       },
//       lastMileTravelString: "4.4 kms",
//       hasSurge: false,
//       sla: {
//         restaurantId: "52670",
//         deliveryTime: 28,
//         minDeliveryTime: 28,
//         maxDeliveryTime: 28,
//         lastMileTravel: 4.400000095367432,
//         lastMileDistance: 0,
//         serviceability: "SERVICEABLE",
//         rainMode: "NONE",
//         longDistance: "NOT_LONG_DISTANCE",
//         preferentialService: false,
//         iconType: "EMPTY",
//       },
//       promoted: true,
//       avgRating: "3.9",
//       totalRatings: 100,
//       new: false,
//     },
//     subtype: "basic",
//   },
//   {
//     type: "restaurant",
//     data: {
//       type: "F",
//       id: "48021",
//       name: "New Punjab",
//       uuid: "e7996696-1ca1-4b43-bc2f-e67fbf319943",
//       city: "5",
//       area: "Vashi",
//       totalRatingsString: "20+ ratings",
//       cloudinaryImageId: "axv7muxiticecrdv3ngf",
//       cuisines: ["Biryani", "North Indian", "Chinese", "Indian"],
//       tags: [],
//       costForTwo: 45000,
//       costForTwoString: "₹450 FOR TWO",
//       deliveryTime: 20,
//       minDeliveryTime: 20,
//       maxDeliveryTime: 20,
//       slaString: "20 MINS",
//       lastMileTravel: 0.4000000059604645,
//       slugs: {
//         restaurant: "new-mini-punjab-kopar-khairane-vashi",
//         city: "mumbai",
//       },
//       cityState: "5",
//       address:
//         "7, Proviso Tower, Plot 14, Sector 16, Kopar Khairane, Navi Mumbai",
//       locality: "Kopar Khairane",
//       parentId: 147304,
//       unserviceable: false,
//       veg: false,
//       select: false,
//       favorite: false,
//       tradeCampaignHeaders: [],
//       aggregatedDiscountInfo: {
//         header: "50% off",
//         shortDescriptionList: [
//           {
//             meta: "50% off | Use WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "50% off up to ₹100 | Use code WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       aggregatedDiscountInfoV2: {
//         header: "50% OFF",
//         shortDescriptionList: [
//           {
//             meta: "Use WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "50% off up to ₹100 | Use code WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       chain: [],
//       feeDetails: {
//         fees: [],
//         totalFees: 0,
//         message: "",
//         title: "",
//         amount: "",
//         icon: "",
//       },
//       availability: {
//         opened: true,
//         nextOpenMessage: "",
//         nextCloseMessage: "",
//       },
//       longDistanceEnabled: 0,
//       rainMode: "NONE",
//       thirdPartyAddress: false,
//       thirdPartyVendor: "",
//       adTrackingID: "",
//       badges: {
//         imageBased: [],
//         textBased: [],
//         textExtendedBadges: [],
//       },
//       lastMileTravelString: "0.4 kms",
//       hasSurge: false,
//       sla: {
//         restaurantId: "48021",
//         deliveryTime: 20,
//         minDeliveryTime: 20,
//         maxDeliveryTime: 20,
//         lastMileTravel: 0.4000000059604645,
//         lastMileDistance: 0,
//         serviceability: "SERVICEABLE",
//         rainMode: "NONE",
//         longDistance: "NOT_LONG_DISTANCE",
//         preferentialService: false,
//         iconType: "EMPTY",
//       },
//       promoted: false,
//       avgRating: "3.7",
//       totalRatings: 20,
//       new: false,
//     },
//     subtype: "basic",
//   },
//   {
//     type: "restaurant",
//     data: {
//       type: "F",
//       id: "34932",
//       name: "Burger King",
//       uuid: "c5b841a4-846c-439c-b7ec-88f4947f2a76",
//       city: "5",
//       area: "Ghansoli",
//       totalRatingsString: "1000+ ratings",
//       cloudinaryImageId: "lmwtgfi9cbeyickcuv4p",
//       cuisines: ["Burgers", "American"],
//       tags: [],
//       costForTwo: 35000,
//       costForTwoString: "₹350 FOR TWO",
//       deliveryTime: 25,
//       minDeliveryTime: 25,
//       maxDeliveryTime: 25,
//       slaString: "25 MINS",
//       lastMileTravel: 2.799999952316284,
//       slugs: {
//         restaurant: "burger-king-vashi-3",
//         city: "mumbai",
//       },
//       cityState: "5",
//       address: "At sector 3, next to Ghansoli station",
//       locality: "Navi Mumbai",
//       parentId: 166,
//       unserviceable: false,
//       veg: false,
//       select: false,
//       favorite: false,
//       tradeCampaignHeaders: [],
//       aggregatedDiscountInfo: {
//         header: "60% off",
//         shortDescriptionList: [
//           {
//             meta: "60% off | Use STEALDEAL",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "60% off up to ₹120 | Use code STEALDEAL",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       aggregatedDiscountInfoV2: {
//         header: "60% OFF",
//         shortDescriptionList: [
//           {
//             meta: "Use STEALDEAL",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "60% off up to ₹120 | Use code STEALDEAL",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       chain: [],
//       feeDetails: {
//         fees: [],
//         totalFees: 0,
//         message: "",
//         title: "",
//         amount: "",
//         icon: "",
//       },
//       availability: {
//         opened: true,
//         nextOpenMessage: "",
//         nextCloseMessage: "",
//       },
//       longDistanceEnabled: 0,
//       rainMode: "NONE",
//       thirdPartyAddress: false,
//       thirdPartyVendor: "",
//       adTrackingID: "",
//       badges: {
//         imageBased: [],
//         textBased: [],
//         textExtendedBadges: [],
//       },
//       lastMileTravelString: "2.7 kms",
//       hasSurge: false,
//       sla: {
//         restaurantId: "34932",
//         deliveryTime: 25,
//         minDeliveryTime: 25,
//         maxDeliveryTime: 25,
//         lastMileTravel: 2.799999952316284,
//         lastMileDistance: 0,
//         serviceability: "SERVICEABLE",
//         rainMode: "NONE",
//         longDistance: "NOT_LONG_DISTANCE",
//         preferentialService: false,
//         iconType: "EMPTY",
//       },
//       promoted: false,
//       avgRating: "4.3",
//       totalRatings: 1000,
//       new: false,
//     },
//     subtype: "basic",
//   },
//   {
//     type: "restaurant",
//     data: {
//       type: "F",
//       id: "21430",
//       name: "KFC",
//       uuid: "43814bad-9f83-444c-93ad-54cdc06cb0f0",
//       city: "5",
//       area: "Vashi",
//       totalRatingsString: "500+ ratings",
//       cloudinaryImageId: "bdcd233971b7c81bf77e1fa4471280eb",
//       cuisines: ["American", "Snacks", "Biryani"],
//       tags: [],
//       costForTwo: 40000,
//       costForTwoString: "₹400 FOR TWO",
//       deliveryTime: 29,
//       minDeliveryTime: 29,
//       maxDeliveryTime: 29,
//       slaString: "29 MINS",
//       lastMileTravel: 5,
//       slugs: {
//         restaurant: "kfc-inorbit-mall-vashi",
//         city: "mumbai",
//       },
//       cityState: "5",
//       address: "Ground Floor, Inorbit Mall, Sector 30 A, Vashi, Navi Mumbai",
//       locality: "Inorbit Mall",
//       parentId: 547,
//       unserviceable: false,
//       veg: false,
//       select: false,
//       favorite: false,
//       tradeCampaignHeaders: [],
//       aggregatedDiscountInfo: {
//         header: "50% off",
//         shortDescriptionList: [
//           {
//             meta: "50% off | Use WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "50% off up to ₹100 | Use code WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       aggregatedDiscountInfoV2: {
//         header: "50% OFF",
//         shortDescriptionList: [
//           {
//             meta: "Use WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "50% off up to ₹100 | Use code WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       ribbon: [
//         {
//           type: "PROMOTED",
//         },
//       ],
//       chain: [],
//       feeDetails: {
//         fees: [],
//         totalFees: 0,
//         message: "",
//         title: "",
//         amount: "",
//         icon: "",
//       },
//       availability: {
//         opened: true,
//         nextOpenMessage: "",
//         nextCloseMessage: "",
//       },
//       longDistanceEnabled: 0,
//       rainMode: "NONE",
//       thirdPartyAddress: false,
//       thirdPartyVendor: "",
//       adTrackingID: "cid=5698086~p=10~eid=00000185-8b34-0265-0ed7-a88100b80a31",
//       badges: {
//         imageBased: [],
//         textBased: [],
//         textExtendedBadges: [],
//       },
//       lastMileTravelString: "5 kms",
//       hasSurge: false,
//       sla: {
//         restaurantId: "21430",
//         deliveryTime: 29,
//         minDeliveryTime: 29,
//         maxDeliveryTime: 29,
//         lastMileTravel: 5,
//         lastMileDistance: 0,
//         serviceability: "SERVICEABLE",
//         rainMode: "NONE",
//         longDistance: "NOT_LONG_DISTANCE",
//         preferentialService: false,
//         iconType: "EMPTY",
//       },
//       promoted: true,
//       avgRating: "4.2",
//       totalRatings: 500,
//       new: false,
//     },
//     subtype: "basic",
//   },
//   {
//     type: "restaurant",
//     data: {
//       type: "F",
//       id: "307090",
//       name: "SHREE CANTEEN",
//       uuid: "f9e74bb4-0ce7-4485-9d07-7e5a4544e92f",
//       city: "5",
//       area: "Kopar Khairane",
//       totalRatingsString: "50+ ratings",
//       cloudinaryImageId: "ke81ssr0ytxflbfnbq2z",
//       cuisines: ["Chinese"],
//       tags: [],
//       costForTwo: 15000,
//       costForTwoString: "₹150 FOR TWO",
//       deliveryTime: 24,
//       minDeliveryTime: 24,
//       maxDeliveryTime: 24,
//       slaString: "24 MINS",
//       lastMileTravel: 0.5,
//       slugs: {
//         restaurant: "shree-canteen-vashi-vashi",
//         city: "mumbai",
//       },
//       cityState: "5",
//       address:
//         "Dyan Vikas Tennis Centre, Kopar Khairane Rd, Sector 17, Kopar Khairane, Navi Mumbai, Maharashtra, India",
//       locality: "Vashi",
//       parentId: 184364,
//       unserviceable: false,
//       veg: false,
//       select: false,
//       favorite: false,
//       tradeCampaignHeaders: [],
//       aggregatedDiscountInfo: {
//         header: "50% off",
//         shortDescriptionList: [
//           {
//             meta: "50% off | Use WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "50% off up to ₹100 | Use code WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       aggregatedDiscountInfoV2: {
//         header: "50% OFF",
//         shortDescriptionList: [
//           {
//             meta: "Use WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "50% off up to ₹100 | Use code WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       chain: [],
//       feeDetails: {
//         fees: [],
//         totalFees: 0,
//         message: "",
//         title: "",
//         amount: "",
//         icon: "",
//       },
//       availability: {
//         opened: true,
//         nextOpenMessage: "",
//         nextCloseMessage: "",
//       },
//       longDistanceEnabled: 0,
//       rainMode: "NONE",
//       thirdPartyAddress: false,
//       thirdPartyVendor: "",
//       adTrackingID: "",
//       badges: {
//         imageBased: [],
//         textBased: [],
//         textExtendedBadges: [],
//       },
//       lastMileTravelString: "0.5 kms",
//       hasSurge: false,
//       sla: {
//         restaurantId: "307090",
//         deliveryTime: 24,
//         minDeliveryTime: 24,
//         maxDeliveryTime: 24,
//         lastMileTravel: 0.5,
//         lastMileDistance: 0,
//         serviceability: "SERVICEABLE",
//         rainMode: "NONE",
//         longDistance: "NOT_LONG_DISTANCE",
//         preferentialService: false,
//         iconType: "EMPTY",
//       },
//       promoted: false,
//       avgRating: "4.0",
//       totalRatings: 50,
//       new: false,
//     },
//     subtype: "basic",
//   },
//   {
//     type: "restaurant",
//     data: {
//       type: "F",
//       id: "39085",
//       name: "Mamledar Misal",
//       uuid: "94ebb620-21da-4a14-a9d5-f2c019afd2c6",
//       city: "5",
//       area: "Kopar Khairane",
//       totalRatingsString: "500+ ratings",
//       cloudinaryImageId: "aelwhoijbaxclmb3ehyw",
//       cuisines: ["Maharashtrian"],
//       tags: [],
//       costForTwo: 20000,
//       costForTwoString: "₹200 FOR TWO",
//       deliveryTime: 14,
//       minDeliveryTime: 14,
//       maxDeliveryTime: 14,
//       slaString: "14 MINS",
//       lastMileTravel: 0.5,
//       slugs: {
//         restaurant: "mamledar-misal-sector-15-vashi",
//         city: "mumbai",
//       },
//       cityState: "5",
//       address:
//         "shop no 1, T J complex, Near Manmohan Mithaiwala, behind gulabsons dairy, sector 15, koparkhairane",
//       locality: "sector 15",
//       parentId: 2906,
//       unserviceable: false,
//       veg: true,
//       select: false,
//       favorite: false,
//       tradeCampaignHeaders: [],
//       aggregatedDiscountInfo: {
//         header: "50% off",
//         shortDescriptionList: [
//           {
//             meta: "50% off | Use WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "50% off up to ₹100 | Use code WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       aggregatedDiscountInfoV2: {
//         header: "50% OFF",
//         shortDescriptionList: [
//           {
//             meta: "Use WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "50% off up to ₹100 | Use code WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       chain: [],
//       feeDetails: {
//         fees: [],
//         totalFees: 0,
//         message: "",
//         title: "",
//         amount: "",
//         icon: "",
//       },
//       availability: {
//         opened: true,
//         nextOpenMessage: "",
//         nextCloseMessage: "",
//       },
//       longDistanceEnabled: 0,
//       rainMode: "NONE",
//       thirdPartyAddress: false,
//       thirdPartyVendor: "",
//       adTrackingID: "",
//       badges: {
//         imageBased: [],
//         textBased: [],
//         textExtendedBadges: [],
//       },
//       lastMileTravelString: "0.5 kms",
//       hasSurge: false,
//       sla: {
//         restaurantId: "39085",
//         deliveryTime: 14,
//         minDeliveryTime: 14,
//         maxDeliveryTime: 14,
//         lastMileTravel: 0.5,
//         lastMileDistance: 0,
//         serviceability: "SERVICEABLE",
//         rainMode: "NONE",
//         longDistance: "NOT_LONG_DISTANCE",
//         preferentialService: false,
//         iconType: "EMPTY",
//       },
//       promoted: false,
//       avgRating: "4.2",
//       totalRatings: 500,
//       new: false,
//     },
//     subtype: "basic",
//   },
//   {
//     type: "restaurant",
//     data: {
//       type: "F",
//       id: "29039",
//       name: "Rajdhani",
//       uuid: "062eb67c-623b-4d38-a193-5abc226346e5",
//       city: "5",
//       area: "Vashi",
//       totalRatingsString: "100+ ratings",
//       cloudinaryImageId: "rajzi2hxhbvoziwifttb",
//       cuisines: ["Rajasthani", "Thalis", "Indian"],
//       tags: [],
//       costForTwo: 40000,
//       costForTwoString: "₹400 FOR TWO",
//       deliveryTime: 30,
//       minDeliveryTime: 30,
//       maxDeliveryTime: 30,
//       slaString: "30 MINS",
//       lastMileTravel: 3.700000047683716,
//       slugs: {
//         restaurant: "rajdhani-vashi-vashi",
//         city: "mumbai",
//       },
//       cityState: "5",
//       address:
//         "Khandani Rajdhani,Shop No 7, Ground Floor, Satra Plaza, Palm Beach Rd, Sector 19D, Vashi, Navi Mumbai, Maharashtra 400703",
//       locality: "Palm Beach Rd",
//       parentId: 753,
//       unserviceable: false,
//       veg: false,
//       select: false,
//       favorite: false,
//       tradeCampaignHeaders: [],
//       aggregatedDiscountInfo: {
//         header: "50% off",
//         shortDescriptionList: [
//           {
//             meta: "50% off | Use WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "50% off up to ₹100 | Use code WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       aggregatedDiscountInfoV2: {
//         header: "50% OFF",
//         shortDescriptionList: [
//           {
//             meta: "Use WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "50% off up to ₹100 | Use code WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       ribbon: [
//         {
//           type: "PROMOTED",
//         },
//       ],
//       chain: [],
//       feeDetails: {
//         fees: [],
//         totalFees: 0,
//         message: "",
//         title: "",
//         amount: "",
//         icon: "",
//       },
//       availability: {
//         opened: true,
//         nextOpenMessage: "",
//         nextCloseMessage: "",
//       },
//       longDistanceEnabled: 0,
//       rainMode: "NONE",
//       thirdPartyAddress: false,
//       thirdPartyVendor: "",
//       adTrackingID: "cid=5666132~p=13~eid=00000185-8b34-0265-0ed7-a88200b80d79",
//       badges: {
//         imageBased: [],
//         textBased: [],
//         textExtendedBadges: [],
//       },
//       lastMileTravelString: "3.7 kms",
//       hasSurge: false,
//       sla: {
//         restaurantId: "29039",
//         deliveryTime: 30,
//         minDeliveryTime: 30,
//         maxDeliveryTime: 30,
//         lastMileTravel: 3.700000047683716,
//         lastMileDistance: 0,
//         serviceability: "SERVICEABLE",
//         rainMode: "NONE",
//         longDistance: "NOT_LONG_DISTANCE",
//         preferentialService: false,
//         iconType: "EMPTY",
//       },
//       promoted: true,
//       avgRating: "4.0",
//       totalRatings: 100,
//       new: false,
//     },
//     subtype: "basic",
//   },
//   {
//     type: "restaurant",
//     data: {
//       type: "F",
//       id: "355926",
//       name: "New Maha Punjab",
//       uuid: "1a88d135-73f4-447c-8be4-d19a8aef4146",
//       city: "5",
//       area: "Kopar Khairane",
//       totalRatingsString: "20+ ratings",
//       cloudinaryImageId: "lqswysxdrldishyeptfm",
//       cuisines: ["Tandoor", "Chinese", "Indian", "North Indian"],
//       tags: [],
//       costForTwo: 35000,
//       costForTwoString: "₹350 FOR TWO",
//       deliveryTime: 21,
//       minDeliveryTime: 21,
//       maxDeliveryTime: 21,
//       slaString: "21 MINS",
//       lastMileTravel: 0.4000000059604645,
//       slugs: {
//         restaurant: "new-maha-punjab-vashi-vashi",
//         city: "mumbai",
//       },
//       cityState: "5",
//       address:
//         "6 Classic Skylark Building, Plot 21 Sector 15, Kopar Khairane, Navi Mumbai",
//       locality: "Vashi",
//       parentId: 147178,
//       unserviceable: false,
//       veg: false,
//       select: false,
//       favorite: false,
//       tradeCampaignHeaders: [],
//       aggregatedDiscountInfo: {
//         header: "50% off",
//         shortDescriptionList: [
//           {
//             meta: "50% off | Use WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "50% off up to ₹100 | Use code WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       aggregatedDiscountInfoV2: {
//         header: "50% OFF",
//         shortDescriptionList: [
//           {
//             meta: "Use WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "50% off up to ₹100 | Use code WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       chain: [],
//       feeDetails: {
//         fees: [],
//         totalFees: 0,
//         message: "",
//         title: "",
//         amount: "",
//         icon: "",
//       },
//       availability: {
//         opened: true,
//         nextOpenMessage: "",
//         nextCloseMessage: "",
//       },
//       longDistanceEnabled: 0,
//       rainMode: "NONE",
//       thirdPartyAddress: false,
//       thirdPartyVendor: "",
//       adTrackingID: "",
//       badges: {
//         imageBased: [],
//         textBased: [],
//         textExtendedBadges: [],
//       },
//       lastMileTravelString: "0.4 kms",
//       hasSurge: false,
//       sla: {
//         restaurantId: "355926",
//         deliveryTime: 21,
//         minDeliveryTime: 21,
//         maxDeliveryTime: 21,
//         lastMileTravel: 0.4000000059604645,
//         lastMileDistance: 0,
//         serviceability: "SERVICEABLE",
//         rainMode: "NONE",
//         longDistance: "NOT_LONG_DISTANCE",
//         preferentialService: false,
//         iconType: "EMPTY",
//       },
//       promoted: false,
//       avgRating: "2.8",
//       totalRatings: 20,
//       new: false,
//     },
//     subtype: "basic",
//   },
//   {
//     type: "restaurant",
//     data: {
//       type: "F",
//       id: "20873",
//       name: "Mansoor Bhai's Lucky",
//       uuid: "385e7a8a-1fa7-458d-a520-abb823005c00",
//       city: "5",
//       area: "Vashi",
//       totalRatingsString: "500+ ratings",
//       cloudinaryImageId: "jmbtcyk3wqkt9kw9ss5o",
//       cuisines: [
//         "Biryani",
//         "Chinese",
//         "North Indian",
//         "Indian",
//         "Tandoor",
//         "Mughlai",
//       ],
//       tags: [],
//       costForTwo: 50000,
//       costForTwoString: "₹500 FOR TWO",
//       deliveryTime: 33,
//       minDeliveryTime: 33,
//       maxDeliveryTime: 33,
//       slaString: "33 MINS",
//       lastMileTravel: 4.400000095367432,
//       slugs: {
//         restaurant: "mansoor-bhais-lucky-sector-18-vashi-vashi",
//         city: "mumbai",
//       },
//       cityState: "5",
//       address:
//         "18/19/20, Ram Lakshman, Sector 18, Vashi, Navi Mumbai, Maharashtra 400705",
//       locality: "Near Janata Bazaar",
//       parentId: 132309,
//       unserviceable: false,
//       veg: false,
//       select: false,
//       favorite: false,
//       tradeCampaignHeaders: [],
//       aggregatedDiscountInfo: {
//         header: "50% off",
//         shortDescriptionList: [
//           {
//             meta: "50% off | Use WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "50% off up to ₹100 | Use code WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       aggregatedDiscountInfoV2: {
//         header: "50% OFF",
//         shortDescriptionList: [
//           {
//             meta: "Use WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "50% off up to ₹100 | Use code WELCOME50",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       ribbon: [
//         {
//           type: "PROMOTED",
//         },
//       ],
//       chain: [],
//       feeDetails: {
//         fees: [],
//         totalFees: 0,
//         message: "",
//         title: "",
//         amount: "",
//         icon: "",
//       },
//       availability: {
//         opened: true,
//         nextOpenMessage: "",
//         nextCloseMessage: "",
//       },
//       longDistanceEnabled: 0,
//       rainMode: "NONE",
//       thirdPartyAddress: false,
//       thirdPartyVendor: "",
//       adTrackingID: "cid=5670678~p=16~eid=00000185-8b34-0265-0ed7-a88300b81022",
//       badges: {
//         imageBased: [],
//         textBased: [],
//         textExtendedBadges: [],
//       },
//       lastMileTravelString: "4.4 kms",
//       hasSurge: false,
//       sla: {
//         restaurantId: "20873",
//         deliveryTime: 33,
//         minDeliveryTime: 33,
//         maxDeliveryTime: 33,
//         lastMileTravel: 4.400000095367432,
//         lastMileDistance: 0,
//         serviceability: "SERVICEABLE",
//         rainMode: "NONE",
//         longDistance: "NOT_LONG_DISTANCE",
//         preferentialService: false,
//         iconType: "EMPTY",
//       },
//       promoted: true,
//       avgRating: "4.1",
//       totalRatings: 500,
//       new: false,
//     },
//     subtype: "basic",
//   },
// ];

export default IMG_CDN_URL =
  "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/";

export const FETCH_MENU_URL =
  "https://www.swiggy.com/dapi/menu/v4/full?lat=19.0998095&lng=72.9993223&menuId=";
